// An initial draft of this test was generated by AI based on a previously written C# test
// every test has been manually adjusted by hand to work with the apiService and tests
// src/services/__tests__/apiService.test.js
import * as apiService from '../apiService';
import jest from 'jest-mock';
// Test credentials
const testEmail = 'user@example.com';
const testUsername = 'TestUser';
const testPassword = 'TestPassword123!';
const testProfileData = {
    name: 'Test User',
    birthDate: '2000-01-01T00:00:00',
    region: 'Test Region',
    profilePicture: '',
    description: 'Test description'
};
const testGroupData = {
    title: `Test Group ${Date.now()}`,
    isVisible: true,
    ageRange: "0 - 99",
    maxMembers: 10,
    description: 'Integration test group',
    tags: ["D&D"]
};
let authToken = null;
let userId = null;
let createdGroupId = null;
// Add this at the top of your test file
const localStorageMock = (() => {
    let store = {};
    return {
        getItem: jest.fn(key => store[key] || null),
        setItem: jest.fn((key, value) => {
            store[key] = value.toString();
        }),
        removeItem: jest.fn(key => {
            delete store[key];
        }),
        clear: jest.fn(() => {
            store = {};
        })
    };
})();
global.localStorage = localStorageMock;

// Skip tests flag - set to true if API is unreachable
let skipTests = false;

// Check API connectivity before tests
beforeAll(async () => {
    try {
        const backEndAddress = apiService.API_BASE.replace(/\/api$/, '');
        const healthCheckUrl = `${backEndAddress}/healthz`;
        const response = await fetch(healthCheckUrl);
        console.log(`Checking endpoint health at: ${healthCheckUrl}`);
        let responseText = await response.text();
        console.log(`Response status: ${responseText}`);
        if (!(responseText === 'Healthy')) {
            console.warn('API is not reachable. Skipping integration tests.');
            skipTests = true;
        }
    } catch (error) {
        console.warn(`Failed to connect to API: ${error.message}`);
        skipTests = true;
        throw new Error(`API is not reachable. Skipping integration tests. ${error.message}`);
    }
}, 10000);

describe('API Service Integration Tests', () => {
    // 1. Registration Test
    test('registers a new user', async () => {
        console.log('registers a new user test starting...');
        if (skipTests) return;

        try {
            const result = await apiService.register(testEmail, testUsername, testPassword);
            expect(result).toHaveProperty('message');
            expect(typeof result.message).toBe('string');
        } catch (error) {
            if (error.message.includes('already taken')) {
                console.log('Test user already exists, continuing...');
            } else {
                throw error;
            }
        }
    }, 10000);

    // 2. Login Test
    test('logs in with valid credentials', async () => {
        if (skipTests) return;
        console.log('logs in with valid credentials test starting...');
        const result = await apiService.login(testEmail, testPassword);
        expect(result).toHaveProperty('token');

        // Save for other tests
        authToken = result.token;
        userId = result.userId;
        localStorage.setItem('token', authToken);
    }, 10000);

    // 3. Create User Profile Test
    test('updates a user profile', async () => {
        if (skipTests)
        {
            console.log('Skipping update user profile test');
            return;
        }
        if (!authToken) {
            console.log('Skipping update user profile test - no auth token');
            return;
            }
        console.log('updates a user profile test starting...');

        const result = await apiService.updateUserProfile({
            body: JSON.stringify(testProfileData)
        });
        expect(result).toHaveProperty('message');
        expect(result.message).toBe('Profile updated successfully!');
    }, 10000);


    // 4. Fetch User Profile Test
    test('fetches user profile', async () => {
        if (skipTests)
        {
            console.log('Skipping update user profile test');
            return;
        }
        if (!authToken) {
            console.log('Skipping update user profile test - no auth token');
            return;
        }

        console.log('fetches user profile test starting...');
        const result = await apiService.fetchUserProfile();
        expect(result).toHaveProperty('description');
        expect(result).toHaveProperty('username');
        expect(result).toHaveProperty('region');
        expect(result).toHaveProperty('birthDate');
        expect(result.username).toBe(testUsername);
        expect(result.region).toBe(testProfileData.region);
        expect(result.birthDate).toBe(testProfileData.birthDate);
        expect(result.description).toBe(testProfileData.description);
    }, 10000);

    // 5. Create Group Test
    test('create a new group', async () => {
        if (skipTests)
        {
            console.log('Skipping new group test');
            return;
        }
        if (!authToken) {
            console.log('Skipping update new group test - no auth token');
            return;
        }
        console.log('create a new group test starting...');
        const result = await apiService.createGroup(testGroupData);

        expect(result).toHaveProperty('message');
        expect(result.message).toBe('Group created successfully!');
    }, 10000);

    // 6. Fetch Groups Test
    test('fetches all groups', async () => {
        if (skipTests)
        {
            console.log('Skipping fetch groups test');
            return;
        }
        if (!authToken) {
            console.log('Skipping fetch groups - no auth token');
            return;
        }
        console.log('fetches all groups test starting...');
        const result = await apiService.fetchGroups();
        expect(Array.isArray(result)).toBe(true);

        if (createdGroupId) {
            const foundGroup = result.find(group => group.id === createdGroupId);
            expect(foundGroup).toBeDefined();
            compareGroups(foundGroup);
            // Save the group ID for later tests
            createdGroupId = foundGroup.id;
        }
    }, 10000);

    // 7. Fetch User Groups Test
    test('fetches user groups', async () => {
        if (skipTests)
        {
            console.log('Skipping fetch user groups test');
            return;
        }
        if (!authToken) {
            console.log('Skipping fetch user groups - no auth token');
            return;
        }
        console.log('fetches user groups test starting...');
        const result = await apiService.fetchUserGroups();
        expect(Array.isArray(result)).toBe(true);
        if (createdGroupId) {
            const foundGroup = result.find(group => group.id === createdGroupId);
            expect(foundGroup).toBeDefined();
            compareGroups(foundGroup);
        }
    }, 10000);

    // 8. Fetch Group By ID Test
    test('fetches a specific group by ID', async () => {
        createdGroupId = localStorage.getItem('groupId');
        if (skipTests)
        {
            console.log('Skipping fetch user groups test');
            return;
        }
        if (!authToken) {
            console.log('Skipping fetch user groups - no auth token');
            return;
        }
        if (!createdGroupId) {
            console.log('Skipping fetch user groups test - no group ID saved');
            return;
        }
        console.log('fetches group by ID test starting...');
        const result = await apiService.fetchGroupById(createdGroupId);
        expect(result).toHaveProperty('id');
        const foundGroup = result.find(group => group.id === createdGroupId);
        expect(foundGroup).toBeDefined();
        compareGroups(foundGroup);

    }, 10000);

    // 9. Leave Group Test
    test('leaves a group', async () => {
        if (skipTests)
        {
            console.log('Skipping update fetch user groups test');
            return;
        }
        if (!authToken) {
            console.log('Skipping update fetch user groups test - no auth token');
            return;
        }
        if (!createdGroupId) {
            console.log('Skipping update fetch user groups test - no group ID saved');
            return;
        }

        const result = await apiService.leaveGroup(createdGroupId);
        expect(result).toBeDefined();
    }, 10000);

    // 10. Join Group Test
    test('joins a group', async () => {
        if (skipTests)
        {
            console.log('Skipping joins a group test');
            return;
        }
        if (!authToken) {
            console.log('Skipping joins a group test - no auth token');
            return;
        }
        if (!createdGroupId) {
            console.log('Skipping joins a group test - no group ID saved');
            return;
        }

        const result = await apiService.joinGroup(createdGroupId);
        expect(result).toBeDefined();
    }, 10000);

    // 11. Update User Profile Test
    test('update user profile', async () => {
        if (skipTests || !authToken) return;
        const result = await apiService.updateUserProfile({
            body: JSON.stringify(testProfileData)
        });

        expect(result).toHaveProperty('message');
        expect(result.message).toBe('Profile updated successfully!');
    }, 10000);

    // 12. Fetch Profile by ID Test
    test('fetches another user profile by ID', async () => {
        if (skipTests || !authToken || !userId) return;

        // This is getting our own profile by ID for simplicity
        const result = await apiService.fetchProfile(userId);
        expect(result).toHaveProperty('id');
        expect(result.id).toBe(userId);
    }, 10000);

    // 13. Accept join request Group Test
    test('accepts a user into group (conditional test)', async () => {
        if (skipTests || !authToken || !createdGroupId) {
            console.log('Skipping accept user test - requires special setup');
            return;
        }

        // Only run if there's another userId to test with (would need separate setup)
        const otherUserId = process.env.TEST_OTHER_USER_ID;
        if (!otherUserId) {
            console.log('Skipping accept/reject user tests - no test user ID provided');
            return;
        }

        try {
            const result = await apiService.AcceptUserIntoGroup(createdGroupId, otherUserId);
            expect(result).toBeDefined();
        } catch (error) {
            // This may fail if user isn't in pending state
            console.log('Accept user test failed, likely due to test preconditions');
        }
    }, 10000);
    // 14. Reject join request Group Test
    test('rejects a user from group (conditional test)', async () => {
        if (skipTests || !authToken || !createdGroupId) {
            console.log('Skipping reject user test - requires special setup');
            return;
        }

        // Only run if there's another userId to test with (would need separate setup)
        const otherUserId = process.env.TEST_OTHER_USER_ID;
        if (!otherUserId) return;

        try {
            const result = await apiService.RejectUserFromGroup(createdGroupId, otherUserId);
            expect(result).toBeDefined();
        } catch (error) {
            // This may fail if user isn't in pending state
            console.log('Reject user test failed, likely due to test preconditions');
        }
    }, 10000);
});

function compareGroups(foundGroup) {
    expect(foundGroup).toBeDefined();
    expect(foundGroup.title).toBe(testGroupData.title);
    expect(foundGroup.description).toBe(testGroupData.description);
    expect(foundGroup.isVisible).toBe(testGroupData.isVisible);
    expect(foundGroup.ageRange).toBe(testGroupData.ageRange);
    expect(foundGroup.maxMembers).toBe(testGroupData.maxMembers);
    expect(foundGroup.tags).toEqual(testGroupData.tags);
}
