x-common-env: &common-env
  ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT:-Development}
  ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
  JwtSettings__SecretKey: ${JWT_SECRET}
  JwtSettings__Issuer: "GameTogether"
  JwtSettings__Audience: "GameTogetherApp"
  EmailSettings__VerificationUrl: ${EMAIL_VERIFICATION_URL}
  EmailSettings__SmtpServer: ${SMTP_SERVER}
  EmailSettings__Port: ${SMTP_PORT}
  EmailSettings__SenderEmail: ${SENDER_EMAIL}
  EmailSettings__SenderPassword: ${SENDER_PASSWORD}
  ASPNETCORE_URLS: ${ASPNETCORE_URLS}
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnet-dev.pfx"
  ASPNETCORE_Kestrel__Certificates__Default__Password: ${DB_PASSWORD:-rekt123}

services:
  # Frontend (React + Nginx)
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile  # Dockerfile for the frontend
    ports:
      - "443:443"  # Expose HTTPS port for frontend
    depends_on:
      - api  # Ensure the backend is up before starting the frontend
    environment:
      - NODE_ENV=production  # Set environment to production for React
    networks:
      - app-network

  # Backend (ASP.NET Core)
  api:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT:-Development}
    ports: ["5000:8080", "7191:7191"]  # Expose backend API on port 5000 (or adjust as needed)
    depends_on:
      mysql:
        condition: service_healthy  # Make sure MySQL is available before starting the backend
      migrate:
        condition: service_completed_successfully
      cert-generator:
        condition: service_completed_successfully
    environment: *common-env
    volumes:
      - ./backend/certs:/https:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7191/healthz"]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - app-network

  # MySQL Database (optional, if your backend requires it)
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports: ["3306:3306"]  # Expose MySQL port 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 2
    networks:
      - app-network

  cert-generator:
    build:
      context: .
      target: build
    environment:
      - DB_PASSWORD=${DB_PASSWORD:-rekt123}
    working_dir: /src
    command: >
      sh -c "mkdir -p /certs &&
      dotnet dev-certs https --clean &&
      dotnet dev-certs https --trust &&
      dotnet dev-certs https -ep /certs/aspnet-dev.pfx -p ${DB_PASSWORD:-rekt123} &&
      chmod 644 /certs/aspnet-dev.pfx &&
      echo 'Certificate generated successfully' > /certs/cert-complete"

  # Migration service to run migrations
  migrate:
    build:
      context: ./backend
      target: build  # Build target for migrations
    depends_on:
      mysql:
        condition: service_healthy
      cert-generator:
        condition: service_completed_successfully
    environment: *common-env
    working_dir: /src
    command: >
      sh -c "dotnet ef database update --project GameTogetherAPI/GameTogetherAPI.csproj --startup-project GameTogetherAPI/GameTogetherAPI.csproj"
    volumes:
      - ./backend/certs:/https:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
