x-common-env: &common-env
  ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
  ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
  JwtSettings__SecretKey: ${JWT_SECRET}
  JwtSettings__Issuer: "GameTogether"
  JwtSettings__Audience: "GameTogetherApp"
  EmailSettings__VerificationUrl: ${EMAIL_VERIFICATION_URL}
  EmailSettings__SmtpServer: ${SMTP_SERVER}
  EmailSettings__Port: ${SMTP_PORT}
  EmailSettings__SenderEmail: ${SENDER_EMAIL}
  EmailSettings__SenderPassword: ${SENDER_PASSWORD}
  ASPNETCORE_URLS: ${ASPNETCORE_URLS}
  #ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnet-dev.pfx"
  ASPNETCORE_Kestrel__Certificates__Default__Password: ${DB_PASSWORD:-rekt123}
  FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}

services:
  test:
    build:
      context: ./frontend
      target: build
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      api:
        condition: service_healthy
    environment: *common-env
    working_dir: /src
    command: >
      npm test
    networks:
      - app-network
