x-common-env: &common-env
  ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
  ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
  JwtSettings__SecretKey: ${JWT_SECRET}
  JwtSettings__Issuer: "GameTogether"
  JwtSettings__Audience: "GameTogetherApp"
  EmailSettings__VerificationUrl: ${EMAIL_VERIFICATION_URL}
  EmailSettings__SmtpServer: ${SMTP_SERVER}
  EmailSettings__Port: ${SMTP_PORT}
  EmailSettings__SenderEmail: ${SENDER_EMAIL}
  EmailSettings__SenderPassword: ${SENDER_PASSWORD}
  ASPNETCORE_URLS: ${ASPNETCORE_URLS}
  #ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnet-dev.pfx"
  ASPNETCORE_Kestrel__Certificates__Default__Password: ${DB_PASSWORD:-rekt123}
  FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}

services:
  # Frontend (React + Nginx)
# Frontend service in Docker-Compose.yml
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
      - API_URL=http://localhost:7191
      - VITE_PORT=5173
      - ENVIRONMENT=${ENVIRONMENT:-Development}
    networks:
      - app-network

  # MySQL Database (optional, if your backend requires it)
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports: ["3306:3306"]  # Expose MySQL port 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 2
    networks:
      - app-network

# Backend (ASP.NET Core)
  api:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    ports: ["5000:8080", "7191:7191"]
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment: *common-env
    volumes:
      - ./backend/certs:/https:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:7191/healthz"]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - app-network

  # Migration service to run migrations
  migrate:
    build:
      context: ./backend
      args:
        - ENVIRONMENT=${ENVIRONMENT}
      target: build
    depends_on:
      mysql:
        condition: service_healthy
    environment: *common-env
    working_dir: /src
    command: >
      sh -c "dotnet ef database update --project GameTogetherAPI/GameTogetherAPI.csproj --startup-project GameTogetherAPI/GameTogetherAPI.csproj"
    volumes:
      - ./backend/certs:/https:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
