name: Test Project
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - test-backend

jobs:
  run-tests:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: 'latest'

      - name: Run frontend tests
        id: frontend-test
        continue-on-error: true
        run: |
          /usr/bin/docker compose up test --exit-code-from test
          echo "status=$?" >> $GITHUB_OUTPUT

      - name: Run backend tests
        id: backend-test
        continue-on-error: true
        run: |
          /usr/bin/docker compose up unittest --exit-code-from unittest
          echo "status=$?" >> $GITHUB_OUTPUT

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            frontend/test-results/
            backend/test-results/

      - name: Fail workflow if any tests failed
        run: |
          frontend_status=${{ steps.frontend-test.outputs.status }}
          backend_status=${{ steps.backend-test.outputs.status }}
          if [ "$frontend_status" != "0" ] || [ "$backend_status" != "0" ]; then
            echo "Frontend tests exit code: $frontend_status"
            echo "Backend tests exit code: $backend_status"
            exit 1
          fi