on:
  push:
    branches:
      - test-fixing
  pull_request:
    branches:
      - main
      - gha-fixing

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: 'latest'

      - name: Run tests and capture exit code
        id: test-run
        run: |
          /usr/bin/docker compose up test --exit-code-from test
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            frontend/test-results/
          # backend/test-results/ We currently do not have working backend unit tests

      - name: Fail workflow if tests failed
        if: steps.test-run.outputs.exit_code != 0
        run: exit ${{ steps.test-run.outputs.exit_code }}
